// Board generation at 10x10 (levels 500+, see @3doku/shared's sizeForLevel)
// is expensive and wildly variable - a real benchmark across levels 500-509
// ranged from 162ms to 62 SECONDS per level, because the repair-based
// uniqueness algorithm sometimes needs several random restarts at this size.
// Two things follow from that:
//   1. It has to run in a worker thread (generationWorker.ts), never on the
//      main thread, or the whole server freezes for everyone for up to a
//      minute at a time.
//   2. Waiting for it on-demand (the instant a player first reaches a new
//      10x10 level) would still mean THAT player stares at a loading screen
//      for up to a minute - so this module proactively generates the next
//      several 10x10 levels in the background, well before anyone actually
//      reaches them, so the normal on-demand path (puzzles.ts's getLevel)
//      almost always just finds them already sitting in the DB.
import { Worker } from 'node:worker_threads';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { sizeForLevel } from '@3doku/shared';
import { getStoredLevel, storeLevel, getRecentStoredRegionsJson } from './db.js';

const dirname = path.dirname(fileURLToPath(import.meta.url));
const workerPath = path.join(dirname, 'generationWorker.js');

// Matches puzzles.ts's own DEDUP_WINDOW - how many of the most recent
// same-size levels a new one must differ from.
const DEDUP_WINDOW = 40;

const PREGENERATE_FROM_LEVEL = 500;
const PREGENERATE_LOOKAHEAD = 10;

interface GeneratedPuzzle {
  size: number;
  regions: number[][];
}

export function generateInWorker(levelIndex: number, excludeRegionsJson: string[]): Promise<GeneratedPuzzle> {
  return new Promise((resolve, reject) => {
    const worker = new Worker(workerPath, { workerData: { levelIndex, excludeRegionsJson } });
    worker.once('message', (msg: GeneratedPuzzle) => {
      resolve(msg);
      worker.terminate();
    });
    worker.once('error', (err) => {
      reject(err);
      worker.terminate();
    });
  });
}

// Only one background pass runs at a time - if a second request for a
// level >= 500 comes in while a pass is already filling in the lookahead
// buffer, there's nothing useful for a second concurrent pass to do (it
// would just find everything already stored or already being generated by
// the first one).
let running = false;

/**
 * Fire-and-forget: call this after resolving any request for a level
 * number >= 500 (see puzzles.ts). Fills in whichever of the next
 * PREGENERATE_LOOKAHEAD levels after `afterLevelIndex` aren't already
 * stored, one at a time, each in its own worker thread.
 */
export function schedulePregeneration(afterLevelIndex: number): void {
  if (afterLevelIndex < PREGENERATE_FROM_LEVEL || running) return;
  running = true;

  (async () => {
    try {
      for (let i = 1; i <= PREGENERATE_LOOKAHEAD; i++) {
        const target = afterLevelIndex + i;
        if (getStoredLevel(target)) continue;
        const exclude = [...getRecentStoredRegionsJson(sizeForLevel(target), DEDUP_WINDOW)];
        const puzzle = await generateInWorker(target, exclude);
        storeLevel(target, puzzle.size, JSON.stringify(puzzle.regions));
      }
    } catch (err) {
      // Best-effort only - a failed background pass just means the normal
      // on-demand path in puzzles.ts falls back to generating that level
      // (via its own worker) the moment it's actually requested.
      console.error('background level pre-generation failed:', err);
    } finally {
      running = false;
    }
  })();
}
